In [1]:
import re
import zipfile
import numpy as np
import pathlib
import rasterio
import geopandas as gpd
import pandas as pd

from tqdm.auto import tqdm
from food_security import data_reader
from rasterio.transform import from_origin, Affine, from_bounds
from rasterio.mask import mask
from rasterio.io import MemoryFile

import matplotlib.pyplot as plt

In [2]:
src_dir = pathlib.Path("~").expanduser().resolve() / "data/food-security"
github_dir = (
    pathlib.Path("~").expanduser().resolve() / "projects/food-security/Food-Security/"
)

In [3]:
communes_gdf = gpd.read_file(src_dir / "Final2_Command_Area.shp")
communes_gdf = communes_gdf.to_crs("EPSG:4326")
communes_gdf

,OBJECTID,Name,Shape_Leng,Shape_Area,Feddan,geometry
0,1,الرشيدية_ومباشر غرب رشيد,121389.174241,3.754359e+08,89389.50,"POLYGON ((30.34442 31.38367, 30.3449 31.38464,..."
1,2,الرياح البحيرى,379980.523243,1.387385e+09,330330.00,"POLYGON ((30.49714 31.11192, 30.52423 31.12877..."
2,6,الخيام,164484.927752,2.457438e+08,58510.40,"POLYGON ((32.06055 26.1862, 32.0578 26.18392, ..."
3,7,نجع حمادى الغربية,541735.552974,1.950372e+09,464374.00,"MULTIPOLYGON (((32.13347 26.10908, 32.13595 26..."
4,8,نجع حمادى الشرقية,385861.370984,6.143672e+08,146278.00,"POLYGON ((31.00797 27.35792, 31.01181 27.35664..."
5,9,الكلابية,334344.834772,7.479556e+08,178085.00,"POLYGON ((32.31197 26.10202, 32.31112 26.10345..."
6,11,ترعة الصف,247397.493839,4.899687e+08,116659.00,"POLYGON ((31.29589 29.95965, 31.29888 29.95779..."
7,12,البحر الصغير,169102.077473,6.934083e+08,165097.00,"MULTIPOLYGON (((31.66716 31.20426, 31.66469 31..."
8,13,النجايل,89164.070500,1.617347e+08,38508.30,"POLYGON ((31.05187 30.31133, 31.05326 30.30991..."
9,14,قنال العنانية,69567.786666,6.687478e+07,15922.60,"MULTIPOLYGON (((31.77007 31.39485, 31.77001 31..."
10,15,البلامون _ الساحل,248901.403537,5.682803e+08,135305.00,"POLYGON ((31.80117 31.47201, 31.80155 31.469, ..."
11,16,الشرقاوية,120670.195430,5.983739e+08,142470.00,"POLYGON ((31.60361 30.55526, 31.60585 30.5525,..."
12,17,البوهية,128027.331374,5.657738e+08,134708.00,"POLYGON ((31.4718 30.76672, 31.47167 30.76694,..."
13,18,بحر شبين,227695.614642,1.304927e+09,310697.00,"POLYGON ((31.16745 30.72426, 31.16743 30.72426..."
14,19,بحر مويس,281979.844735,1.843466e+09,438920.00,"MULTIPOLYGON (((31.60027 30.55561, 31.60072 30..."
15,20,أسوان,755358.494757,1.448439e+09,344866.00,"MULTIPOLYGON (((32.92678 24.74431, 32.92567 24..."
16,21,الرنان الرئيسي,109003.972620,1.746415e+08,41581.30,"POLYGON ((32.49228 26.11167, 32.49504 26.11138..."
17,22,زمام اصفون,242292.235317,3.246991e+08,77309.30,"POLYGON ((32.64874 26.17484, 32.65518 26.17136..."
18,23,زمام الرمادي,103284.777776,2.262998e+08,53880.90,"POLYGON ((32.48669 25.48296, 32.50433 25.48022..."
19,24,زمام الكلابية القديمة,45239.055900,4.359444e+07,10379.60,"POLYGON ((32.57463 25.37824, 32.57936 25.36845..."
20,25,ابوحمار,35283.229044,5.976739e+07,14230.30,"POLYGON ((32.14171 26.16976, 32.14454 26.16278..."
21,26,الرنان الشرقي_بخانس,71339.871393,1.535572e+08,36561.20,"POLYGON ((32.05693 26.15217, 32.09029 26.12327..."
22,27,مباشر نيل,440607.015302,2.347692e+08,55897.40,"MULTIPOLYGON (((30.89034 27.41556, 30.89197 27..."
23,28,عمر بك,71886.744291,1.007574e+08,23989.90,"POLYGON ((31.22036 30.84091, 31.21932 30.84001..."
24,29,جنابية دهتورة,19519.801737,1.079042e+07,2569.15,"POLYGON ((31.21967 30.80897, 31.22057 30.80733..."
25,30,العطف,116190.657305,4.933201e+08,117457.00,"POLYGON ((31.20182 30.75551, 31.2016 30.7548, ..."
26,31,البحر الصعيدي,69542.655002,1.913176e+08,45551.80,"POLYGON ((30.67002 31.40261, 30.67786 31.39477..."
27,32,خليج القني,20435.139266,1.820244e+07,4333.91,"POLYGON ((30.56246 31.28819, 30.55488 31.2798,..."
28,33,بحر بسنديلة _ بلقاس _ تيرة,236771.991064,1.818626e+09,433006.00,"POLYGON ((31.40589 31.13072, 31.38769 31.13271..."
29,34,السلام,304083.244938,9.971843e+08,237425.00,"POLYGON ((31.79847 31.28267, 31.79923 31.2797,..."
30,35,الباجورية,228446.895459,8.882516e+08,211488.00,"POLYGON ((30.91432 31.08777, 30.91424 31.08778..."
31,36,دروة وراضى,72970.788021,5.093019e+07,12126.20,"POLYGON ((31.09876 30.37619, 31.09747 30.37447..."
32,37,الباسوسية,127801.857000,2.623758e+08,62470.40,"POLYGON ((31.34344 30.47083, 31.34182 30.4687,..."
33,38,أبو المنجا,110830.420956,2.991833e+08,71234.10,"MULTIPOLYGON (((31.11555 30.31566, 31.11587 30..."
34,39,ترعة البستان,132924.732070,8.413742e+08,200327.00,"POLYGON ((30.37607 30.61018, 30.44921 30.58266..."
35,40,ترعة النصر,348502.131941,1.466091e+09,349069.00,"POLYGON ((29.70778 30.83411, 29.71036 30.83311..."
36,41,الرياح الناصرى,189154.586343,4.032182e+08,96004.30,"POLYGON ((30.67922 30.70454, 30.67999 30.70373..."
37,42,ترعة سيناء,228408.192093,6.009114e+08,143074.00,"POLYGON ((32.32711 30.57756, 32.35132 30.67114..."
38,43,ترعة المنايف,81242.775718,3.968343e+08,94484.30,"POLYGON ((32.18285 30.56816, 32.19248 30.56523..."
39,44,ترعة بورسعيد,158218.180406,1.998280e+08,47578.10,"POLYGON ((32.30828 31.0238, 32.30846 31.01846,..."
40,45,ترعة السويس,241200.663414,4.279141e+08,101884.00,"POLYGON ((32.28471 30.55316, 32.28841 30.54964..."
41,46,ترعي الصالحية و السعيدية,177227.006184,1.058180e+09,251948.00,"POLYGON ((32.12755 30.86196, 32.12402 30.81785..."
42,47,ترعة الإسماعيلية,358672.555488,1.657309e+09,394597.00,"POLYGON ((31.73509 30.68554, 31.73475 30.68331..."
43,48,الرياح التوفيقى,181335.427857,5.172151e+08,123146.00,"POLYGON ((31.34582 30.87346, 31.34609 30.8711,..."
44,49,بحر طناح,116242.118633,3.425843e+08,81567.70,"POLYGON ((31.89942 31.0746, 31.89817 31.0744, ..."
45,50,المنصورية,86295.515439,2.406144e+08,57289.10,"POLYGON ((31.41496 31.06874, 31.4152 31.06811,..."
46,51,الشرقاوية_ من المنصورية,146848.436093,2.840497e+08,67630.90,"POLYGON ((31.76416 31.39144, 31.76462 31.39329..."
47,52,النوبارية,540522.768222,2.392990e+09,569759.00,"POLYGON ((29.8793 31.05455, 29.87992 31.05451,..."
48,53,المحمودية,258304.418666,1.203503e+09,286548.00,"POLYGON ((30.05393 31.29429, 30.05232 31.29239..."
49,54,ميت يزيد,204307.451596,1.118941e+09,266414.00,"POLYGON ((30.96521 31.46005, 30.96581 31.45477..."
50,55,الرياح العباسى,171993.414128,5.345701e+08,127279.00,"POLYGON ((31.40485 31.12397, 31.40398 31.11813..."
51,56,زمام الرشدية_وسط الدلتا,110445.263979,2.196591e+08,52299.80,"MULTIPOLYGON (((30.40455 31.47208, 30.42761 31..."
52,57,الرياح المنوفى,217246.533904,7.091952e+08,168856.00,"POLYGON ((30.84543 30.81231, 30.8435 30.7935, ..."
53,58,الابراهيمية,862976.326243,2.632504e+09,626787.00,"POLYGON ((30.72474 27.87707, 30.73037 27.87828..."
54,59,بحر حسن واصف,431221.584178,7.670328e+08,182627.00,"MULTIPOLYGON (((30.50862 29.19402, 30.50706 29..."
55,60,البحر اليوسفي_الفيوم,247492.890070,1.117079e+09,265971.00,"POLYGON ((30.96891 29.23009, 30.97392 29.22245..."
56,62,ترعة سري باشا,285344.080271,4.608900e+08,109736.00,"POLYGON ((30.72474 27.87707, 30.72447 27.87964..."
57,63,ترعة الشيخ جابر,148008.629916,6.495025e+08,154643.00,"POLYGON ((32.31723 31.01515, 32.31703 31.02067..."
58,65,البحر اليوسفي,600629.783332,1.055013e+09,251194.00,"POLYGON ((30.96925 29.19997, 30.97048 29.19902..."
59,77,ترعة الجيزة,353243.598171,6.138948e+08,146165.00,"POLYGON ((31.05675 30.21855, 31.05761 30.21856..."

In [4]:
def create_population_raster(zip_file, tif_file, tfw_file):
    # Get correct transform from tfw file. Order seems to be messed up.
    with zipfile.ZipFile(zip_file, "r") as z:
        with z.open(tfw_file) as f:
            lines = f.read().decode().splitlines()
            a = float(lines[0])
            b = float(lines[1])
            c = float(lines[4])
            d = float(lines[2])
            e = float(lines[3])
            f_ = float(lines[5])

    transform = Affine(a, b, c, d, e, f_)

    with rasterio.open(f"zip+file://{zip_file}!/{tif_file}") as src:
        data = src.read()

        # Update transform of tif, since there seems to be an error in the original transform
        profile = src.profile
        profile.update({"transform": transform})

    # Create and write to a tif file in memory
    raster_file = MemoryFile()
    dst = raster_file.open(**profile)
    dst.write(data[0, ...], 1)

    return dst


def read_zipped_tif_file(zip_file, tif_file):
    # print(f'zip+file://{zip_file}!/{tif_file}')
    src = rasterio.open(f"zip+file://{zip_file}!/{tif_file}")
    return src

In [5]:
gdp_files = {
    "SSP1": {
        "zip": "/Users/hemert/data/food-security/ssp/7898409/SSP1.zip",
        "tif": "SSP1/GDP2050_ssp1.tif",
    },
    "SSP2": {
        "zip": "/Users/hemert/data/food-security/ssp/7898409/SSP2.zip",
        "tif": "SSP2/GDP2050_ssp2.tif",
    },
    "SSP3": {
        "zip": "/Users/hemert/data/food-security/ssp/7898409/SSP3.zip",
        "tif": "SSP3/GDP2050_ssp3.tif",
    },
    "SSP4": {
        "zip": "/Users/hemert/data/food-security/ssp/7898409/SSP4.zip",
        "tif": "SSP4/GDP2050_ssp4.tif",
    },
    "SSP5": {
        "zip": "/Users/hemert/data/food-security/ssp/7898409/SSP5.zip",
        "tif": "SSP5/GDP2050_ssp5.tif",
    },
}
pop_files = {
    "SSP1": {
        "zip": "/Users/hemert/data/food-security/ssp/19608594/SPP1.zip",
        "tif": "SPP1/SSP1_2050.tif",
        "tfw": "SPP1/SSP1_2050.tfw",
    },
    "SSP2": {
        "zip": "/Users/hemert/data/food-security/ssp/19608594/SSP2.zip",
        "tif": "SPP2/SSP2_2050.tif",
        "tfw": "SPP2/SSP2_2050.tfw",
    },
    "SSP3": {
        "zip": "/Users/hemert/data/food-security/ssp/19608594/SSP3.zip",
        "tif": "SPP3/SSP3_2050.tif",
        "tfw": "SPP3/SSP3_2050.tfw",
    },
    "SSP4": {
        "zip": "/Users/hemert/data/food-security/ssp/19608594/SSP4.zip",
        "tif": "SPP4/SSP4_2050.tif",
        "tfw": "SPP4/SSP4_2050.tfw",
    },
    "SSP5": {
        "zip": "/Users/hemert/data/food-security/ssp/19608594/SSP5.zip",
        "tif": "SPP5/SSP5_2050.tif",
        "tfw": "SPP5/SSP5_2050.tfw",
    },
}

In [6]:
def zonal_statistics(geometry, raster):
    masked_raster = mask(raster, geometry, nodata=np.nan, all_touched=False)[0]
    geometry_sum = np.nansum(masked_raster)

    return geometry_sum

In [7]:
SSPs = ["SSP1", "SSP2", "SSP3", "SSP4", "SSP5"]
names = communes_gdf["Name"].values
df_dict = {
    "ssp": [],
    "area_name": [],
    "GDP": [],
    "population": [],
}
for ssp in tqdm(SSPs):
    # print(ssp)
    gdp_raster = read_zipped_tif_file(gdp_files[ssp]["zip"], gdp_files[ssp]["tif"])
    pop_raster = create_population_raster(
        pop_files[ssp]["zip"], pop_files[ssp]["tif"], pop_files[ssp]["tfw"]
    )

    for name in tqdm(names):
        commune_geometry = communes_gdf[communes_gdf["Name"] == name]["geometry"]

        gdp = zonal_statistics(commune_geometry, gdp_raster)
        pop = zonal_statistics(commune_geometry, pop_raster)

        df_dict["ssp"].append(ssp)
        df_dict["area_name"].append(name)
        df_dict["GDP"].append(gdp)
        df_dict["population"].append(pop)

df = pd.DataFrame(df_dict)

  0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/60 [00:00<?, ?it/s]

  0%|          | 0/60 [00:00<?, ?it/s]

In [9]:
df.to_csv(src_dir / "ssp_gdp_and_pop_egypt.csv")

In [8]:
df

      ssp                 area_name           GDP    population
0    SSP1  الرشيدية_ومباشر غرب رشيد  6.872697e+09  4.216201e+05
1    SSP1            الرياح البحيرى  6.496647e+10  2.805288e+06
2    SSP1                    الخيام  7.873758e+09  6.994701e+05
3    SSP1         نجع حمادى الغربية  1.881752e+11  8.254078e+06
4    SSP1         نجع حمادى الشرقية  4.238746e+10  2.253231e+06
..    ...                       ...           ...           ...
295  SSP5      البحر اليوسفي_الفيوم  1.102102e+11  3.658177e+06
296  SSP5             ترعة سري باشا  1.791008e+10  1.083392e+06
297  SSP5           ترعة الشيخ جابر  5.279346e+07  1.731888e+04
298  SSP5             البحر اليوسفي  1.913953e+10  1.013994e+06
299  SSP5               ترعة الجيزة  4.535584e+11  5.428275e+06

[300 rows x 4 columns]